# Permalinks
permalink:           /:categories/:title

# Setup
title:               Wicked Good Data
tagline:             'Website and blog of Daniel P. Martin'
description:         'Quantitative Psychology PhD and Data Scientist at McKinsey & Company.'
url:                 http://dpmartin42.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dan Martin
  email:             dpmartin42@gmail.com

# Set up google analytics

analytics :
  provider : google
  google : 
      tracking_id : 'UA-123-12'
  getclicky :
    site_id : UA-26032429-1

# Custom vars
version:             1.0.0
